### ISSUE TITLE
Version number is off

### ISSUE THREAD

**Issue by JamesStuder** [kowgli/XrmToolbox.ManagedSolutionSitemapFixer#1]
Can you please fix the version number so the update will remove from the plugin store in XRMToolbox.  Right now it shows latest version as 1.0.1 and installed version as 1.0.0.0.  Even after checking it to update.  It never goes away.  Thank you.

**Comment by kowgli** [comment]
Hi James,

I was not aware the assembly version number has a connection to the nuget package number. I can change both to 1.0.2 if that helps.

**Comment by kowgli** [comment]
Done. NuGet package is validating. Thanks for bringing this to my attention.
